#!/bin/sh

# Install the java dbus service
rm -f /usr/lib/luna/java/org.webosinternals.accelservice.jar
ln -s /var/usr/lib/luna/java/org.webosinternals.accelservice.jar /usr/lib/luna/java/org.webosinternals.accelservice.jar
rm -f /usr/share/dbus-1/system-services/org.webosinternals.accelservice.service
ln -s /var/usr/share/dbus-1/system-services/org.webosinternals.accelservice.service /usr/share/dbus-1/system-services/org.webosinternals.accelservice.service

# Install the upstart script
rm -f /etc/event.d/org.webosinternals.accelservice
cp /var/etc/event.d/org.webosinternals.accelservice /etc/event.d/org.webosinternals.accelservice

# Restart the service handler (this also starts this service)
if [ -z "$IPKG_OFFLINE_ROOT" ]; then # Defined by recent installers that also support flags.
    /sbin/stop java-serviceboot
    /sbin/start java-serviceboot
fi

exit 0
