#!/bin/sh

# Install the java dbus service
rm -f /usr/lib/luna/java/org.webosinternals.accelservice.jar
cp $IPKG_OFFLINE_ROOT/usr/lib/luna/java/org.webosinternals.accelservice.jar /usr/lib/luna/java/org.webosinternals.accelservice.jar
rm -f /usr/share/dbus-1/system-services/org.webosinternals.accelservice.service
cp $IPKG_OFFLINE_ROOT/usr/share/dbus-1/system-services/org.webosinternals.accelservice.service /usr/share/dbus-1/system-services/org.webosinternals.accelservice.service

# Install the upstart script
rm -f /etc/event.d/org.webosinternals.accelservice
cp $IPKG_OFFLINE_ROOT/etc/event.d/org.webosinternals.accelservice /etc/event.d/org.webosinternals.accelservice

exit 0
